site_name: "API Viniviticultura"
theme:
  name: material
  logo: images/Logo-icon-white.png
  favicon: images/Logo-icon.png
  custom_dir: overrides
  features:
    - content.tabs.link
docs_dir: .
site_dir: ../site
extra_css:
  - stylesheets/bootstrap.min.css
  - stylesheets/styles.min.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
    custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Apresentação: index.md
  - Arquitetura do Projeto: arquitetura_projeto.md
  - Documentação da API: documentacao_api.md
  - Fluxo de Scraping: fluxo_scraping.md
  - Modelos de Dados: modelos_dados.md
  - Estrutura dos Arquivos: estrutura_arquivos.md
