version: "3.8"

services:
  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  api:
    build: ./api
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "80:8000"
    restart: always
    networks:
      - mynetwork
    volumes:
      - ./api:/app # Mount the api directory for development changes

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
